services: 
  app:
    image: "shootkiran/mims:app"
    container_name: "mims-app"
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - "./:/var/www/html"
    restart: always
    networks:
       - mims-network
    logging:
      driver: json-file
      options: 
        max-file: "1"
        max-size: "10k"
networks:
  mims-network:
     driver: bridge
volumes:
  redis_data:
