version: "3.8"

services:
  app:
    image: shootkiran/laravel:latest
    container_name: laravel12_app
    ports:
      - "8500:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    restart: unless-stopped