version: "3.8"

services:
  app:
    #build:
    #  context: .
    #  dockerfile: docker/Dockerfile
    image: shootkiran/laravel
    # platform: linux/amd64
    # container_name: laravel12_app
#    ports:
#       - "8600:80"
    volumes:
      - ./web:/var/www/html
    # working_dir: /var/www/html
    # restart: unless-stopped
